[package]
org = "ballerina"
name = "websub_tests"
version = "2.15.1"

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
path = "../native/build/libs/websub-native-2.15.1-SNAPSHOT.jar"
